server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL}
  server:
    wait-time-in-ms-when-sync-empty: 5
    
logging:
  file:
    name: /home/discovery-service/logs/DiscoveryService.log
  level:
    root: WARN